version: "3.7"

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - microservice
    networks:
      - grpc-network

  microservice:
    build:
      context: microservice
      dockerfile: Dockerfile
    networks:
      - grpc-network

networks:
  grpc-network:
